### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by 23BCA281** [vtcbca/internal-exam-23BCA281#2]
![er](https://github.com/user-attachments/assets/3fb762a3-08ed-4f7c-add2-0e73196c69cb)
can anyone please solve this error.

**Comment by 23bca274** [comment]
don't write "the" before contact

**Comment by 23BCA284** [comment]
please upload your hole code or try to removing "the" may be your table name is only contact.

**Comment by 23BCA281** [comment]
I truly appreciate all of your helpful suggestions, which helped me a lot.
