### ISSUE TITLE
please upload your hole code or try to removing "the" may be your table name is only contact.

### ISSUE THREAD

**Issue by 23BCA281** [vtcbca/internal-exam-23BCA281#3]
please upload your hole code or try to removing "the" may be your table name is only contact.

_Originally posted by @23BCA284 in https://github.com/vtcbca/internal-exam-23BCA281/issues/2#issuecomment-2348069738_

**Comment by 23BCA281** [comment]
> ```
>           please upload your hole code or try to removing "the" may be your table name is only contact.
> ```
> 
> _Originally posted by @23BCA284 in [#2 (comment)](https://github.com/vtcbca/internal-exam-23BCA281/issues/2#issuecomment-2348069738)_

![image](https://github.com/user-attachments/assets/66d9b8d3-6468-443b-9bcf-f8eff91c7ddc)

**Comment by 23bca274** [comment]
Please upload your Jupyter Python code, the screenshot is too blur to understand !

**Comment by 23BCA281** [comment]
Thank you all of you for your valuable suggestions which helped me a lot.
